USE [master]
GO

/****** Object:  Database [DP]    Script Date: 07/27/2013 12:13:10 ******/
CREATE DATABASE [DP] ON  PRIMARY 
( NAME = N'DP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008\MSSQL\DATA\DP.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008\MSSQL\DATA\DP.ldf' , SIZE = 291904KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DP] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DP].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [DP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DP] SET ARITHABORT OFF 
GO

ALTER DATABASE [DP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DP] SET  READ_WRITE 
GO

ALTER DATABASE [DP] SET RECOVERY FULL 
GO

ALTER DATABASE [DP] SET  MULTI_USER 
GO

ALTER DATABASE [DP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DP] SET DB_CHAINING OFF 
GO


